/* See LICENSE file for copyright and license details. */
#include <stdio.h>

typedef unsigned char u8;
typedef unsigned short int u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short int s16;
typedef signed int s32;
typedef float f32;

typedef enum {
	REFID_CATEGORY_TABLES = 0X0100,
	REFID_CATEGORY_PARAMETERS = 0X0200,
	REFID_CATEGORY_CODECS = 0X0300,
	REFID_CATEGORY_GENERAL = 0X1F00,

	REFID_CATEGORY_SOUNDARCHIVEFILE_BLOCKS = 0X2000,
	REFID_CATEGORY_SOUNDARCHIVEFILE_INFOSECTIONS = 0X2100,
	REFID_CATEGORY_SOUNDARCHIVEFILE_ITEMINFOS = 0X2200,
	REFID_CATEGORY_SOUNDARCHIVEFILE_PARAMETERS = 0X2300,
	REFID_CATEGORY_SOUNDARCHIVEFILE_GENERAL = 0X2400,

	REFID_CATEGORY_STREAMSOUNDFILE_BLOCKS = 0X4000,
	REFID_CATEGORY_STREAMSOUNDFILE_ITEMINFOS = 0X4100,

	REFID_CATEGORY_WAVESOUNDFILE_BLOCKS = 0X4800,
	REFID_CATEGORY_WAVESOUNDFILE_ITEMINFOS = 0X4900,

	REFID_CATEGORY_SEQUENCESOUNDFILE_BLOCKS = 0X5000,
	REFID_CATEGORY_SEQUENCESOUNDFILE_ITEMINFOS = 0X5100,

	REFID_CATEGORY_BANKFILE_BLOCKS = 0X5800,
	REFID_CATEGORY_BANKFILE_ITEMS = 0X5900,
	REFID_CATEGORY_BANKFILE_ITEMTABLES = 0X6000,

	REFID_CATEGORY_WAVEARCHIVEFILE_BLOCKS = 0X6800,

	REFID_CATEGORY_WAVEFILE_BLOCKS = 0X7000,
	REFID_CATEGORY_WAVEFILE_ITEMINFOS = 0X7100,

	REFID_CATEGORY_GROUPFILE_BLOCKS = 0X7800,
	REFID_CATEGORY_GROUPFILE_ITEMINFOS = 0X7900,

	REFID_CATEGORY_ANIMSOUNDFILE_BLOCKS = 0X8000,
	REFID_CATEGORY_ANIMSOUNDFILE_ITEMS = 0X8100,

	/* Common Sound */

	REFID_TABLE_EMBEDDINGTABLE = REFID_CATEGORY_TABLES,
	REFID_TABLE_REFERENCETABLE,
	REFID_TABLE_REFERENCEWITHSIZETABLE,

	REFID_PARAMETER_SOUND3D = REFID_CATEGORY_PARAMETERS,
	REFID_PARAMETER_SENDS,
	REFID_PARAMETER_ENVELOPE,
	REFID_PARAMETER_ADSHRENVELOPE,

	REFID_CODEC_DSPADPCMINFO = REFID_CATEGORY_CODECS,
	REFID_CODEC_IMAADPCMINFO,

	REFID_GENERAL_BYTESTREAM = REFID_CATEGORY_GENERAL,
	REFID_GENERAL_STRING,

	/* Sound Archive File */

	REFID_SOUNDARCHIVEFILE_STRINGBLOCK = REFID_CATEGORY_SOUNDARCHIVEFILE_BLOCKS,
	REFID_SOUNDARCHIVEFILE_INFOBLOCK,
	REFID_SOUNDARCHIVEFILE_FILEBLOCK,

	REFID_SOUNDARCHIVEFILE_SOUNDINFOSECTION = REFID_CATEGORY_SOUNDARCHIVEFILE_INFOSECTIONS,
	REFID_SOUNDARCHIVEFILE_BANKINFOSECTION,
	REFID_SOUNDARCHIVEFILE_PLAYERINFOSECTION,
	REFID_SOUNDARCHIVEFILE_WAVEARCHIVEINFOSECTION,
	REFID_SOUNDARCHIVEFILE_SOUNDGROUPINFOSECTION,
	REFID_SOUNDARCHIVEFILE_GROUPINFOSECTION,
	REFID_SOUNDARCHIVEFILE_FILEINFOSECTION,

	REFID_SOUNDARCHIVEFILE_SOUNDINFO = REFID_CATEGORY_SOUNDARCHIVEFILE_ITEMINFOS,
	REFID_SOUNDARCHIVEFILE_STREAMSOUNDINFO,
	REFID_SOUNDARCHIVEFILE_WAVESOUNDINFO,
	REFID_SOUNDARCHIVEFILE_SEQUENCESOUNDINFO,
	REFID_SOUNDARCHIVEFILE_SOUNDGROUPINFO,
	REFID_SOUNDARCHIVEFILE_WAVESOUNDGROUPINFO,
	REFID_SOUNDARCHIVEFILE_BANKINFO,
	REFID_SOUNDARCHIVEFILE_WAVEARCHIVEINFO,
	REFID_SOUNDARCHIVEFILE_GROUPINFO,
	REFID_SOUNDARCHIVEFILE_PLAYERINFO,
	REFID_SOUNDARCHIVEFILE_FILEINFO,
	REFID_SOUNDARCHIVEFILE_SOUNDARCHIVEPLAYERINFO,
	REFID_SOUNDARCHIVEFILE_INTERNALFILEINFO,
	REFID_SOUNDARCHIVEFILE_EXTERNALFILEINFO,
	REFID_SOUNDARCHIVEFILE_STREAMSOUNDTRACKINFO,
	REFID_SOUNDARCHIVEFILE_SENDINFO,
	REFID_SOUNDARCHIVEFILE_STREAMSOUNDEXTENSIONINFO,

	REFID_SOUNDARCHIVEFILE_STRINGTABLE = REFID_CATEGORY_SOUNDARCHIVEFILE_GENERAL,
	REFID_SOUNDARCHIVEFILE_PATRICIATREE,

	/* Stream File */

	REFID_STREAMSOUNDFILE_INFOBLOCK = REFID_CATEGORY_STREAMSOUNDFILE_BLOCKS,
	REFID_STREAMSOUNDFILE_SEEKBLOCK,
	REFID_STREAMSOUNDFILE_DATABLOCK,
	REFID_STREAMSOUNDFILE_REGIONBLOCK,
	REFID_STREAMSOUNDFILE_PREFETCHDATABLOCK,

	REFID_STREAMSOUNDFILE_STREAMSOUNDINFO = REFID_CATEGORY_STREAMSOUNDFILE_ITEMINFOS,
	REFID_STREAMSOUNDFILE_TRACKINFO,
	REFID_STREAMSOUNDFILE_CHANNELINFO,
	REFID_STREAMSOUNDFILE_REGIONINFO,

	/* Web Sound File */

	REFID_WAVESOUNDFILE_INFOBLOCK = REFID_CATEGORY_WAVEARCHIVEFILE_BLOCKS,

	REFID_WAVESOUNDFILE_WAVESOUNDMETADATA = REFID_CATEGORY_WAVESOUNDFILE_ITEMINFOS,
	REFID_WAVESOUNDFILE_WAVESOUNDINFO,
	REFID_WAVESOUNDFILE_NOTEINFO,
	REFID_WAVESOUNDFILE_TRACKINFO,
	REFID_WAVESOUNDFILE_NOTEEVENT,

	/* Waveform Archive File */

	REFID_WAVEARCHIVEFILE_INFOBLOCK = REFID_CATEGORY_WAVEARCHIVEFILE_BLOCKS,
	REFID_WAVEARCHIVEFILE_FILEBLOCK,

	/* Waveform File */

	REFID_WAVEFILE_INFOBLOCK = REFID_CATEGORY_WAVEFILE_BLOCKS,
	REFID_WAVEFILE_DATABLOCK,

	REFID_WAVEFILE_CHANNELINFO = REFID_CATEGORY_WAVEFILE_ITEMINFOS,

	/* Sequence File */

	REFID_SEQUENCESOUNDFILE_DATABLOCK = REFID_CATEGORY_SEQUENCESOUNDFILE_BLOCKS,
	REFID_SEQUENCESOUNDFILE_LABELBLOCK,

	REFID_SEQUENCESOUNDFILE_LABELINFO = REFID_CATEGORY_SEQUENCESOUNDFILE_ITEMINFOS,

	/* Bank File */

	REFID_BANKFILE_INFOBLOCK = REFID_CATEGORY_BANKFILE_BLOCKS,

	REFID_BANKFILE_INSTRUMENTINFO = REFID_CATEGORY_BANKFILE_ITEMS,
	REFID_BANKFILE_KEYREGIONINFO,
	REFID_BANKFILE_VELOCITYREGIONINFO,
	REFID_BANKFILE_NULLINFO,

	REFID_BANKFILE_DIRECTREFERENCETABLE = REFID_CATEGORY_BANKFILE_ITEMTABLES,
	REFID_BANKFILE_RANGEREFERENCETABLE,
	REFID_BANKFILE_INDEXREFERENCETABLE,

	/* Group File */

	REFID_GROUPFILE_INFOBLOCK = REFID_CATEGORY_GROUPFILE_BLOCKS,
	REFID_GROUPFILE_FILEBLOCK,
	REFID_GROUPFILE_INFOEXBLOCK,

	REFID_GROUPFILE_GROUPITEMINFO = REFID_CATEGORY_GROUPFILE_ITEMINFOS,
	REFID_GROUPFILE_GROUPITEMINFOEX,

	/* Animation Sound File */
	REFID_ANIMSOUNDFILE_DATABLOCK = REFID_CATEGORY_ANIMSOUNDFILE_BLOCKS,

	REFID_ANIMSOUNDFILE_EVENTINFO = REFID_CATEGORY_ANIMSOUNDFILE_ITEMS
} ReferenceID;

typedef enum {
	STATUS_OK = 0,
	STATUS_ERR
} Status;

typedef enum {
	FALSE = 0,
	TRUE
} Bool;

struct PointerList {
	u32 count;
	void **pointers;
};

struct FileHeader {
	u32 filePosition;
	char fileType[5];
	u16 byteOrder;
	u16 headerLength;
	u32 fileVersion;
	u32 fileLength;
	u16 partitionCount;
};

struct PartitionHeader {
	u32 filePosition;
	char partitionType[5];
	u32 length;
};

struct Link {
	u32 filePosition;
	ReferenceID referenceID;
	s32 offset;
};

struct LinkWithLength {
	u32 filePosition;
	ReferenceID referenceID;
	s32 offset;
	u32 length;
};

struct LinkTable {
	u32 filePosition;
	u32 count;
	struct Link *table;
};

struct LinkWithLengthTable {
	u32 filePosition;
	u32 count;
	struct LinkWithLength *table;
	u32 size;
};

struct OptionParameter {
	u32 filePosition;
	u32 bitFlag;
};

struct BitFlag {
		u32 bitIndex;
		u32 *destination;
};

struct U8Table {
	u32 filePosition;
	u32 count;
	u8 *table;
};

struct U32Table {
	u32 filePosition;
	u32 count;
	u32 *table;
};

u32
readLittleEndian(FILE *file, u32 bytes);

u32
readBigEndian(FILE *file, u32 bytes);

f32
readFloat(FILE *file, u32 (*readBytes)(FILE *, u32));

Status
setEndianess(u16 byteOrder, u32 (**readBytesPointer)(FILE *, u32));

void
addPointerToPointerList(void *pointer, struct PointerList *pointerList);

void
freePointerList(struct PointerList pointerList);

Status
readFileHeader(struct FileHeader *fileHeader, FILE *file, char fileType[4], u32 (**readBytesPointer)(FILE *, u32));

Status
readPartitionHeader(struct PartitionHeader *partitionHeader, FILE *file, char partitionType[4], u32 (*readBytes)(FILE *file, u32 bytes));

Status
readLink(struct Link *link, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes));

Status
readLinkWithLength(struct LinkWithLength *link, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes));

Status
readLinkTable(struct LinkTable *linkTable, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes), struct PointerList *pointerList);

Status
readLinkWithLengthTable(struct LinkWithLengthTable *linkTable, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes), struct PointerList *pointerList);

Status
getLinkByReferenceID(u32 *out, u32 linkCount, struct Link links[linkCount], ReferenceID referenceID);

Status
getLinkWithLengthByReferenceID(u32 *out, u32 linkCount, struct LinkWithLength links[linkCount], ReferenceID referenceID);

u32
getBitFlagParameterIndex(u32 bitFlag, u32 bitNumber);

Status
readOptionParameter(struct OptionParameter *optionParameter, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes));

u8
getByte(u32 value, u8 index);

Status
readU8Table(struct U8Table *u8Table, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes), struct PointerList *pointerList);

Status
readU32Table(struct U32Table *u32Table, FILE *file, u32 (*readBytes)(FILE *file, u32 bytes), struct PointerList *pointerList);